#!/bin/bash
a=133000000
b=124000000
c=98000000
d=130000000
ovs-vsctl set Interface vhost-user-1 options:limit-cycles=$a
ovs-vsctl set Interface vhost-user-2 options:limit-cycles=$a
ovs-vsctl set Interface vhost-user-3 options:limit-cycles=$a
ovs-vsctl set Interface vhost-user-4 options:limit-cycles=$a
ovs-vsctl set Interface vhost-user-5 options:limit-cycles=$b
ovs-vsctl set Interface vhost-user-6 options:limit-cycles=$b
ovs-vsctl set Interface vhost-user-7 options:limit-cycles=$b
ovs-vsctl set Interface vhost-user-8 options:limit-cycles=$b
ovs-vsctl set Interface vhost-user-9 options:limit-cycles=$d
ovs-vsctl set Interface vhost-user-10 options:limit-cycles=$d
ovs-vsctl set Interface vhost-user-11 options:limit-cycles=$d
ovs-vsctl set Interface vhost-user-12 options:limit-cycles=$d
ovs-vsctl set Interface vhost-user-13 options:limit-cycles=$c
ovs-vsctl set Interface vhost-user-14 options:limit-cycles=100
ovs-vsctl set Interface vhost-user-15 options:limit-cycles=100
ovs-vsctl set Interface vhost-user-25 options:limit-cycles=100
ovs-vsctl set Interface vhost-user-16 options:limit-cycles=$a
ovs-vsctl set Interface vhost-user-17 options:limit-cycles=$a
ovs-vsctl set Interface vhost-user-18 options:limit-cycles=$a
ovs-vsctl set Interface vhost-user-19 options:limit-cycles=100
ovs-vsctl set Interface vhost-user-20 options:limit-cycles=100
ovs-vsctl set Interface vhost-user-21 options:limit-cycles=100
ovs-vsctl set Interface vhost-user-22 options:limit-cycles=100
ovs-vsctl set Interface vhost-user-23 options:limit-cycles=100
ovs-vsctl set Interface vhost-user-24 options:limit-cycles=100
